// Code generated by generate-workout-types.js; DO NOT EDIT.

/**
 * Workout types and configuration
 */

export type WorkoutTypeConfig = {
  value: string;
  location: boolean;
  distance: boolean;
  repetition: boolean;
  weight: boolean;
  duration: boolean;
  pace: boolean;
};

export const WORKOUT_TYPES: WorkoutTypeConfig[] = [
  {
    value: 'running',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: true,
  },
  {
    value: 'cycling',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'e-cycling',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'horse-riding',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'inline-skating',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'walking',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'skiing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'snowboarding',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'swimming',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'kayaking',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'rowing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'golfing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'hiking',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'push-ups',
    location: false,
    distance: false,
    repetition: true,
    weight: false,
    duration: true,
    pace: false,
  },
  {
    value: 'weight-lifting',
    location: false,
    distance: false,
    repetition: true,
    weight: true,
    duration: true,
    pace: false,
  },
  {
    value: 'other',
    location: true,
    distance: true,
    repetition: true,
    weight: true,
    duration: true,
    pace: false,
  },
];

export function getWorkoutTypeConfig(type: string): WorkoutTypeConfig | undefined {
  return WORKOUT_TYPES.find((wt) => wt.value === type);
}
