FROM node:24.14-alpine AS dev-frontend

WORKDIR /app

COPY client/package*.json ./client/
RUN cd client && npm ci

COPY client ./client

WORKDIR /app/client
EXPOSE 4200
ENTRYPOINT ["npm", "run", "start"]

FROM golang:1.26.2-alpine AS dev-backend
ARG BUILD_TIME
ARG GIT_COMMIT
ARG GIT_REF
ARG GIT_REF_NAME
ARG GIT_REF_TYPE

RUN apk --no-cache add make git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile ./
COPY assets ./assets
COPY cmd ./cmd
COPY pkg ./pkg
COPY vendor ./vendor
COPY translations ./translations

ENV CGO_ENABLED=0
ENTRYPOINT ["make", "dev-backend"]
