// Code generated by generate-workout-types; DO NOT EDIT.
package model

const (
	WorkoutTypeRunning       WorkoutType = "running"
	WorkoutTypeCycling       WorkoutType = "cycling"
	WorkoutTypeECycling      WorkoutType = "e-cycling"
	WorkoutTypeHorseRiding   WorkoutType = "horse-riding"
	WorkoutTypeInlineSkating WorkoutType = "inline-skating"
	WorkoutTypeWalking       WorkoutType = "walking"
	WorkoutTypeSkiing        WorkoutType = "skiing"
	WorkoutTypeSnowboarding  WorkoutType = "snowboarding"
	WorkoutTypeSwimming      WorkoutType = "swimming"
	WorkoutTypeKayaking      WorkoutType = "kayaking"
	WorkoutTypeRowing        WorkoutType = "rowing"
	WorkoutTypeGolfing       WorkoutType = "golfing"
	WorkoutTypeHiking        WorkoutType = "hiking"
	WorkoutTypePushups       WorkoutType = "push-ups"
	WorkoutTypeWeightLifting WorkoutType = "weight-lifting"
	WorkoutTypeOther         WorkoutType = "other"
)

var workoutTypeConfigs = map[WorkoutType]WorkoutTypeConfiguration{
	WorkoutTypeRunning:       {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeCycling:       {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeECycling:      {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeHorseRiding:   {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeInlineSkating: {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeWalking:       {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeSkiing:        {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeSnowboarding:  {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeSwimming:      {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeKayaking:      {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeRowing:        {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeGolfing:       {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypeHiking:        {Location: true, Distance: true, Repetition: false, Weight: false},
	WorkoutTypePushups:       {Location: false, Distance: false, Repetition: true, Weight: false},
	WorkoutTypeWeightLifting: {Location: false, Distance: false, Repetition: true, Weight: true},
	WorkoutTypeOther:         {Location: true, Distance: true, Repetition: true, Weight: true},
}
