remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Aepyornis
description: Aepyornis is a social sports-activity sharing app, built on ActivityPub.
navigation:
  - name: Home
    link: ./index.html
  - name: Getting started
    link: ./getting-started.html
  - name: Configuration
    link: ./configuration.html
  - name: API
    link: ./api.html
  - name: ActivityPub
    link: ./acitivitypub.html
  - name: Development
    link: ./development.html
